### ISSUE TITLE
RealSimulator TUSBA R2 not hidden by HidGuardian

### ISSUE THREAD

**Issue by oskargargas** [ViGEm/HidGuardian#3]
Hey,

First of all I'd like to say you've made a great piece of software. I've been looking for something like that for years!

Yesterday I tried HidGuardian with some of hardware I own and I found out that RealSimulator TUSBA R2 (http://www.realsimulator.com/html/tusba.html) which is USB adapter for Thrustmaster Cougar Throttle. It works like a charm with Thrustmaster Warthog stick and MFG Crosswind rudder pedals so I know the problem is just with TUSBA and not with the general use/configuration.

Can I provide you some logs/information/data or test something or do anything else to help make it work? ;) 

Cheers,
Oskar

**Comment by nefarius** [comment]
Give HidHide a shot once binaries are released.
