### ISSUE TITLE
Tag latest stable 1.14.3.0 version

### ISSUE THREAD

**Issue by nanoant** [ViGEm/HidGuardian#4]
Hi,
Can you please tag a commit with `v1.14.3.0` that corresponds to the build at https://downloads.vigem.org/projects/HidGuardian/stable/1.14.3.0/windows/x86/
Thanks in advance.

**Comment by nefarius** [comment]
Aye, makes sense, will do.

**Comment by nefarius** [comment]
I realized why this tag/commit was so hard to find, that version was unfortunately in the source tree of the legacy "all in one" repository I started the very first projects with, therefore the code is even older than what you find here, sorry ☹️
