### ISSUE TITLE
Add whitelist by process exe path to stable 1.x

### ISSUE THREAD

**Issue by nanoant** [ViGEm/HidGuardian#5]
I think much simpler approach than Cerberus / dynamic API that would work for 99% cases/users would be simply to have whitelist based on full process exe path rather than process ID. That would make things like whitelisting DS4Windows or NVIDIA's `nvcontainer.exe` (my case) that provides XBOX controller emulation for NVIDIA shield controller super simple and work after reboots without need to rewrite registry entries, we would need to put path just once to the registry.
I think this should be doable reading:
https://community.osr.com/discussion/183409/current-process-name-in-kernel-driver
https://www.osronline.com/article.cfm%5earticle=472.htm
I would like to try to add modification myself but I have no clue which commit corresponds to latest 1.x stable, hence my other issue #4 
Anyways thanks for this great piece of code, that allowed me to play some games that get confused by NVIDIA shield controller exposing both xinput and dinput devices on PC 😄

**Comment by nefarius** [comment]
That whole overly complicated design comes from a time where I had very little idea what I was actually doing and just made things up as I progressed 😅

**Comment by nefarius** [comment]
Not relevant anymore as this is a core design in HidHide.
