### ISSUE TITLE
(Likely for HidHide since HidGuardian is EOL) Hiding vJoy controllers?

### ISSUE THREAD

**Issue by hifihedgehog** [ViGEm/HidGuardian#8]
See above. I am having to feed my DInput controllers into vJoy with Joystick Gremlin and from there into XOutput to get consolidated virtual XInput controllers. Reason being is to provide seamlessly switching from arcade cabinet controls to on-the-fly connected wireless controllers. My minor issue is I need to hide the vJoy controllers. HidGuardian, in HidCerberus, does not seem to be able to enumerate a vJoy controller as a candidate controller that can be hidden. I try adding it manually, using the HID line taken from...
![image](https://user-images.githubusercontent.com/16614343/103434486-ebb8c380-4bcf-11eb-9249-448fd02d00c9.png)
....to the list of affected devices with HidCerberus but it does not want to propagate. Is there a way to do this or are vJoy devices not supported since they are not "real" controllers?

**Comment by nefarius** [comment]
From my tests I can tell you that HidHide is able to hide the individual vJoy controllers 😁

**Comment by hifihedgehog** [comment]
> From my tests I can tell you that HidHide is able to hide the individual vJoy controllers 😁

Gotta love this teaser. Can't wait! Keeping my eyes peeled for this!

**Comment by nefarius** [comment]
I had a more busy December/January than expected but I'm still on it. Currently writing documentation so the potential flood on questions can be reduced from the start. We're still horribly understaffed after all 😇

**Comment by nefarius** [comment]
Trying to test it again but vJoy setup seems to be stuck forever...

![image](https://user-images.githubusercontent.com/286631/105170162-d4109300-5b1c-11eb-8b8c-08a659fcab9c.png)

**Comment by nefarius** [comment]
Neat, found a bug in the installer causing an infinite hang 😦 

API [`UpdateDriverForPlugAndPlayDevicesA`](https://docs.microsoft.com/en-us/windows/win32/api/newdev/nf-newdev-updatedriverforplugandplaydevicesa) is called in a helper process with [suppressed UI](https://github.com/njz3/vJoy/blob/d56de94a80d931d0b14f10cd676213b38f18d972/apps/vJoyInstall/vJoyInstallLib.cpp#L788), but [`INSTALLFLAG_NONINTERACTIVE`](https://docs.microsoft.com/en-us/windows/win32/api/newdev/nf-newdev-updatedriverforplugandplaydevicesa#installflag_noninteractive) flag is [not used](https://github.com/njz3/vJoy/blob/d56de94a80d931d0b14f10cd676213b38f18d972/apps/vJoyInstall/vJoyInstallLib.cpp#L725), causing a reboot required dialog to appear, which is invisible and inaccessible to the user and therefore blocking the installer indefinitely:

![image](https://user-images.githubusercontent.com/286631/105172242-9bbe8400-5b1f-11eb-9d74-e4676ae326b8.png)

Meh...

**Comment by nefarius** [comment]
Killed the installer helper process and the setup finished 😅 

![image](https://user-images.githubusercontent.com/286631/105173413-42575480-5b21-11eb-86e3-9d75c26bdc44.png)

**Comment by nefarius** [comment]
Here it is in action, default:

![image](https://user-images.githubusercontent.com/286631/105174737-4d12e900-5b23-11eb-9a10-a4955d03b6aa.png)

2 of 3 vJoy devices hidden:

![image](https://user-images.githubusercontent.com/286631/105174838-6ddb3e80-5b23-11eb-9879-9b412cf4468f.png)

**Comment by nefarius** [comment]
And while we're at it; XInput blocking 😁 

Normal:

![image](https://user-images.githubusercontent.com/286631/105179017-12ac4a80-5b29-11eb-91c5-c5c74358bafd.png)

Gone:

![image](https://user-images.githubusercontent.com/286631/105179081-22c42a00-5b29-11eb-96e0-0ce3a5b8c074.png)

**Comment by hifihedgehog** [comment]
\*drooling\*

**Comment by nefarius** [comment]
It's released 😉

**Comment by nefarius** [comment]
Closed as this project is history.
