### ISSUE TITLE
After uninstalling, my computer no longer seems my Switch Pro Controller as a Gamepad. 

### ISSUE THREAD

**Issue by zmarotrix** [ViGEm/HidGuardian#9]
The ONLY way I have found to fix this is to COMPLETELY REINSTALL my OS. I'm on Windows 10.

I've been trying to use HidGuardian with BetterJoy to use my Switch Pro Controller in Cemu/Citra however I noticed I can no longer use my controller in other applications so I tried uninstalling everything and now my computer will connect to my switch Pro via Bluetooth but it will not recognize it as a gamepad. 

I'm going to be reinstalling Windows 10 AGAIN to fix this.

**Comment by nefarius** [comment]
[Removal procedure is outlined here](https://github.com/ViGEm/HidGuardian/tree/master/sys#manual-removal) and works, no need to be so dramatic and wipe Windows 🙂

**Comment by nefarius** [comment]
[Also see here](https://vigem.org/projects/HidGuardian/Taming-HidGuardian-Gen1/).
